name: Clojure CI

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  clojure:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      # We develop on Temurin 21.x, let's use that on CI too
      - uses: actions/setup-java@v5
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Install clojure tools
        uses: DeLaGuardo/setup-clojure@13.4
        with:
          github-token: ''
          # Install just one or all simultaneously
          # The value must indicate a particular version of the tool, or use 'latest'
          # to always provision the latest version
          cli: latest

      - name: Execute clojure tests
        run: clojure -T:build test
